### ISSUE TITLE
Compatible Version of Atlas Quest?

### ISSUE THREAD

**Issue by GenericJohnDoeNO0** [hawaiisa/Atlas#1]
Hi there, is there any compatible version of atlas quest for this package? (That from that legacy site will not work correctly...)

**Comment by KrekoG** [comment]
The originally forked seems to work fine. Make sure you only copy the `AtlasQuest` folder into your addons.
https://github.com/laytya/Atlas

**Comment by hawaiisa** [comment]
As already pointed out by KrekoG, the AtlasQuest in laytya's repo should still be compatible with this one. Apparently it has a small problem with the quest "The Prophecy of Mosh'aru" in Zul'Farak, which could be related to something about Tiara of the Deep. https://github.com/laytya/Atlas

Note that at the time of writing I do not intend on maintaining a version of AtlasQuest for the server, should an update to Atlas(Loot) cause issues.

**Comment by Mishamorj** [comment]
hello, is it possible to modify the atlas of ingredients for recipes?  P.S. this message is via google translate
